# Generated by Django 5.0.7 on 2024-07-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("ingredients", models.TextField()),
                ("instructions", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="recipe_images/"
                    ),
                ),
                ("cooking_time", models.IntegerField(blank=True, null=True)),
                ("servings", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
